/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package game;

import game.TerixState;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.image.BufferedImage;

/**
 *
 * @author wssccc
 */
public class BrickPanel extends javax.swing.JPanel {

    public BufferedImage img;
    int boxSize;
    /**
     * Creates new form BrickPanel
     */
    Color[] colorList = new Color[]{Color.WHITE, Color.BLUE, Color.GRAY};

    public void updateImg(TerixState gs) {

        int size1 = getWidth() / gs.width;
        int size2 = getHeight() / gs.height;
        boxSize = size1 > size2 ? size2 : size1;

        img = new BufferedImage(gs.width * boxSize, gs.height * boxSize, BufferedImage.TYPE_4BYTE_ABGR);
        Graphics g = img.getGraphics();
        g.setColor(Color.WHITE);
        g.fillRect(0, 0, img.getWidth(), img.getHeight());
        //draw solid bricks
        for (int i = 0; i < gs.height; ++i) {
            for (int j = 0; j < gs.width; ++j) {
                int index = gs.data[i * gs.width + j];
                g.setColor(colorList[index]);
                g.fillRect(j * boxSize, i * boxSize, boxSize, boxSize);
            }
        }
        //draw moving brick
        if (gs.brick != null) {
            for (int i = 0; i < Brick.HEIGHT; ++i) {
                for (int j = 0; j < Brick.WIDTH; ++j) {
                    int index = gs.brick.data[i * Brick.WIDTH + j];
                    if (index != 0) {
                        g.setColor(Color.black);
                        g.fillRect((j + gs.brickX) * boxSize, (i + gs.brickY) * boxSize, boxSize, boxSize);
                    }
                }
            }
        }
        //draw lines
        for (int i = 0; i < gs.width; ++i) {
            g.setColor(Color.BLACK);
            g.drawLine(i * boxSize, 0, i * boxSize, gs.height * boxSize);
        }

        for (int i = 0; i < gs.height; ++i) {
            g.setColor(Color.BLACK);
            g.drawLine(0, i * boxSize, gs.width * boxSize, i * boxSize);
        }

        this.repaint();
    }

    public BrickPanel() {
        initComponents();
    }

    @Override
    public void paint(Graphics g) {
        super.paint(g);
        g.drawImage(img, 0, 0, this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
