/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package terix;

import game.TerixState;
import game.ai.TerixAi;
import game.ai.TerixAiCommand;
import game.ai.TerixAiParam;
import game.ai.pso.Vector;
import game.brick.Brick;
import java.awt.event.KeyEvent;
import java.util.Timer;
import java.util.TimerTask;

/**
 *
 * @author wssccc
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    TerixState ts;

    final void initTerix() {
        ts = new TerixState(10, 20);
        ts.setBrick(Brick.createBrick(Brick.BRICK_T));
    }

    public MainWindow() {
        initComponents();
        initTerix();
        brickPanel1.setFocusable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        brickPanel1 = new game.graphics.BrickPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        brickPanel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                brickPanel1KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout brickPanel1Layout = new javax.swing.GroupLayout(brickPanel1);
        brickPanel1.setLayout(brickPanel1Layout);
        brickPanel1Layout.setHorizontalGroup(
            brickPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        brickPanel1Layout.setVerticalGroup(
            brickPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 273, Short.MAX_VALUE)
        );

        jButton1.setText("auto");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("play mode");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(brickPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(brickPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void brickPanel1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_brickPanel1KeyPressed
        // TODO add your handling code here:
        switch (evt.getKeyCode()) {
            case KeyEvent.VK_LEFT:
                ts.moveLeft();
                break;
            case KeyEvent.VK_RIGHT:
                ts.moveRight();
                break;
            case KeyEvent.VK_UP:
                ts.rotateRight();
                break;
            case KeyEvent.VK_DOWN:
                ts.moveDownDirect();
                break;
        }
        brickPanel1.updateImg(ts);
    }//GEN-LAST:event_brickPanel1KeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ts.setBrick(Brick.createBrick(Brick.BRICK_T));
        new Timer().schedule(new TimerTask() {

            int count = 0;

            @Override
            public void run() {

                if (ts.isGameOver()) {
                    System.out.println("Game over,count=" + count);
                    this.cancel();
                }
                Brick next = Brick.randomBrick();
                Brick nexth = next.clone();
                TerixAiParam taconf = new TerixAiParam(new Vector(new float[]{0.8495455f, 0.11494613f, 0.7302942f, 0.14472693f, 0.33341503f}));

                TerixAiCommand tac = new TerixAi(taconf, next).findSteps(ts);
                tac.applyTo(ts);
                ts.setBrick(nexth);
                ++count;
                if (count % 20 == 0) {
                    // ts.growUp(2);
                }
                brickPanel1.updateImg(ts);
            }
        }, 500, 50);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new Timer().schedule(new TimerTask() {

            @Override
            public void run() {

                if (!ts.moveDown()) {
                    ts.fusion();
                    ts.boom();
                    ts.setBrick(Brick.randomBrick());
                }

                brickPanel1.updateImg(ts);
            }
        }, 0, 1000);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void run() {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */

        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private game.graphics.BrickPanel brickPanel1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    // End of variables declaration//GEN-END:variables
}
